### ISSUE TITLE
Openshift Websocket returns nothing!

### ISSUE THREAD

**Issue by andro-galexy** [ramr/openshift-tornado-websockets#2]
I have deployed the repo code to my openshift app here: piot-cloudap.rhcloud.com:8000 when i tries to connect to this URL using python web socket client lib it connects, but when i tries to send something and then receives the data it return empty string, what is the issue do I need to made some changes in the code!

Thanks.

**Comment by ramr** [comment]
@swapgit its something with your app (code). I just tried these instructions and it works fine:  

```
rhc app create tornado python-2.6    
cd tornado   
git remote add upstream -m master git@github.com:ramr/openshift-tornado-websockets.git   
git pull -s recursive -X theirs upstream master   
git push  
```

And access the app:  `http://tornado-$yournamespace.rhcloud.com:8000`
